apiVersion: apps/v1
kind: Deployment
metadata:
  name: current-usa-time-deployment
spec:
  replicas: 2 #  This value means you want two instances of your Pod running concurrently.
  selector:
    matchLabels:
      app: current-usa-time
  template:
    metadata:
      labels:
        app: current-usa-time
    spec:
      containers: # you can give more containers if you want multiple containers to run in single pod
        - name: current-usa-time
          image: seturini/current-usa-time:latest
          ports:
            - containerPort: 7777 # Code port
