apiVersion: apps/v1
kind: Deployment
metadata:
  name: current-usa-time-deployment
spec:
  replicas: 2 # Number of pods
  selector:
    matchLabels:
      app: current-usa-time
  template:
    metadata:
      labels:
        app: current-usa-time
    spec:
      containers:
        - name: current-usa-time
          image: seturini/current-usa-time:latest # Replace with your image name and tag
          ports:
            - containerPort: 7777 # Replace with the port your app listens on
