apiVersion: v1
kind: Service
metadata:
  name: current-usa-time-service
spec:
  selector:
    app: current-usa-time
  ports:
    - protocol: TCP
      port: 9999 # Exposed port
      targetPort: 7777 # code port
  type: LoadBalancer # For external access; use NodePort if LoadBalancer isn't available
