server:
  port: 7777

spring:
  profile: dev
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: kafka-streams-app # Unique application ID for Kafka Streams
      bootstrap-servers: localhost:9092 # Kafka broker for the Streams application
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        commit.interval.ms: 1000  # Commit interval for state stores
        cache.max.bytes.buffering: 10485760  # Max cache size for buffering (10 MB)
        state.dir: /tmp/kafka-streams-state # Directory for state stores
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: my-group
      enable-auto-commit: true      # Automatically commit offsets
      auto-offset-reset: earliest   # Consume from the earliest offset if no offset is found
      auto-commit-interval: 1000ms # Commit offsets every 1 second
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    admin:
      client-id: kafka-admin
